[supabase]
url = "https://hqedqxnyxdmeyoiidluy.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxZWRxeG55eGRtZXlvaWlkbHV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMjYyMDcsImV4cCI6MjA3MjkwMjIwN30.4qbaBF2sAOhqEubt8YnlErb6AVB8INU5M6OfrgyxmDk"
