[supabase]
url = "https://fkbuyqqhjytnjgbjxzma.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrYnV5cXFoanl0bmpnYmp4em1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzMDkwMjUsImV4cCI6MjA1MDg4NTAyNX0.b9gOwa36UWIQA-An-2KxEGsqtg7emrRcfBSNv0si0to"
